import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "../components/footer";
import ChatBot from "@/components/chatbot";

// Import Inter font, but we'll use it selectively
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://api.fontshare.com/v2/css?f[]=satoshi@400,700&f[]=clash-display@400,500&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        {children}
        <ChatBot />
        {/* Footer with Inter font if needed */}
        <Footer  />
      </body>
    </html>
  );
}


